[build]
  builder        = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

  [build.dockerBuildArgs]
    SERVICE = "auth"

[deploy]
  startCommand            = "node dist/apps/auth/main.js"
  restartPolicyType       = "ON_FAILURE"
  restartPolicyMaxRetries = 5
