[build]
  builder        = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

  [build.dockerBuildArgs]
    SERVICE = "gateway"

[deploy]
  startCommand            = "node dist/apps/gateway/main.js"
  healthcheckPath         = "/api/health"
  healthcheckTimeout      = 300
  restartPolicyType       = "ON_FAILURE"
  restartPolicyMaxRetries = 5
