[build]
  builder        = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

[deploy]
  startCommand            = "node dist/apps/storage/main.js"
  restartPolicyType       = "ON_FAILURE"
  restartPolicyMaxRetries = 5
